# -*- coding: utf-8 -*-
"""YFinance_sports.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItOASBUDMUMAOv_OuP2EoEZBfkKwP-7q
"""

!pip install yfinance

import yfinance as yf
import pandas as pd

tickers = ['TATAMOTORS.NS', 'TCS.NS', 'PEP', 'HLF']

all_data = {}

for ticker in tickers:
    try:
        print(f"Downloading data for {ticker}...")
        data = yf.download(ticker, start='2008-01-01', end='2025-01-01')

        if data.empty:
            print(f"Warning: No data found for {ticker}. Skipping.")
            continue

        data = data.add_suffix(f'_{ticker}')
        all_data[ticker] = data

    except Exception as e:
        print(f"Error fetching data for {ticker}: {e}")

if all_data:
    final_df = pd.concat(all_data.values(), axis=1)

    final_df.reset_index(inplace=True)

    final_df.to_csv('ipl_sponsors_stock_data.csv', index=False)
    print("Data collection complete. Saved to 'ipl_sponsors_stock_data.csv'.")
else:
    print("No data collected. Check your tickers and internet connection.")

